[WIP] feat: add orchid driver
Julien-R44/bentocache pull request #17
Opened 2024-04-29 13:04 UTC by bingtsingw

2024-04-29 13:05 UTC, bingtsingw commented
I do not implement `createTableIfNotExists`, is this necessary?

2024-04-29 13:43 UTC, Julien-R44 commented
Cool! Thanks a lot for the PR dude. I came across Orchid ORM a while back and thought it looked like Lucid with other some cool features

> I do not implement createTableIfNotExists, is this necessary?

Yes, bentocache will automatically create the table if `autoCreateTable` is true. This allows seamless use of Bentocache without having to manually create a migration if you're lazy: https://bentocache.dev/docs/cache-drivers#databases. You can refer to the Knex or Kysely driver, it should be pretty easy to implement

> And I can't setup local test, for my new driver and existing drivers, could you please help me run the test?

What's the problem? There's nothing in particular to do other than launch the docker-compose in the repo which starts a postgres. then launch the tests. But let me know if anything else is giving you trouble

Looks we have some lint issues too

2024-04-29 13:44 UTC, Julien-R44 requested changes

2024-04-29 13:44 UTC, Julien-R44 commented on packages/bentocache/package.json
> +    "orchid-orm": "^1.24.0",
Should also be added as peer dependency

2024-04-29 15:02 UTC, bingtsingw commented
@Julien-R44 `lint error` and `peerDependencies` has been fixed.

As for `createTableIfNotExists`, I do not find `createTable` related method from the `#connection`, `Orchid ORM` has a separate package `rake-db` for migrations and table creations, but it's very heavy to import it into runtime, so I don't want to introduce it only for `createTable`.

@romeerez Hi, does `orchid-orm` package provide some lightweight way to `createTable`

2024-04-29 15:33 UTC, romeerez commented
@bingtsingw it's very nice to see this PR!

I'm seeing this Bentocache library for the first time and I'm not sure yet what exactly is required from a db driver.

In some cases, it can be enough to just write a bit of custom SQL to create a table. But looks like in this case, it should happen dynamically.

Imagine that OrchidORM has an exported separate function `createTable`. But how about changing a table? Wouldn't you need much more functionality to add/drop/change/rename columns? No way there is no need to ever change a table.

So I'll look into Bentocache to see what should be changed in Orchid to support it.

2024-04-29 15:41 UTC, bingtsingw commented
@romeerez  Thank you for your support, in `Bentocache`, it has an `autoCreateTable` option which needs  to implement `createTableIfNotExists`, this is the `Kysely` version of implementation:
```ts
  async createTableIfNotExists(): Promise<void> {
    await this.#connection.schema
      .createTable(this.#tableName)
      .addColumn('key', 'varchar(255)', (col) => col.primaryKey().notNull())
      .addColumn('value', 'text')
      .addColumn('expires_at', 'bigint')
      .ifNotExists()
      .execute()
  }
```
There is no need to change it in this situation.

2024-04-29 15:52 UTC, bingtsingw commented
@Julien-R44 Thank you for your explain, I thought it was a must.
@romeerez Seems there is no need to add extra methods, I'll test if it works

2024-04-29 16:07 UTC, romeerez commented
@bingtsingw I have looked around, and, well, any ORM is an overkill for this case, even Knex and Kysely are overkill, since Bentocache requires only limited functionality from a driver, it should be easy enough and better for performance to do all queries (to create a table, get value, set value) with raw SQL by calling `pg` or `postgres` libs directly.

ORM has a ton of additional functionality that won't be used: relations management, various features like callbacks on create/update/delete, `deletedAt`, and many more. Query builder also has a ton of functionality that is redundant for this: various ways of doing joins, and wrappers for various SQL statements.

2024-04-29 16:13 UTC, bingtsingw commented
@romeerez Yes, in fact ORM is overkill for this tiny cache table, that's why I do not use Knex or Kysely and want to implement an orchid driver, cause I already use it in my project, making it a driver of bentocache is natural.

2024-04-29 16:25 UTC, romeerez commented
Aha, yes that makes sense.

In such case, IMO it would be better for Bentocache to have a pg lib adapter, then it could work with any ORM that depends on `pg` driver.

You could extract [pg.Pool](https://node-postgres.com/apis/pool) from the db instance and the Bentocache pg driver would use it for performing queries directly:

```ts
const db = orchidORM({ ...options }, { ...tables })

// extract pg.Pool from db instance:
const pgPool = db.$adapter.pool

const value = await pgPool.query('SELECT value FROM cache WHERE key = ?', ['key'])
```

2024-04-29 16:32 UTC, Julien-R44 commented
> @bingtsingw I have looked around, and, well, any ORM is an overkill for this case, even Knex and Kysely are overkill, since Bentocache requires only limited functionality from a driver, it should be easy enough and better for performance to do all queries (to create a table, get value, set value) with raw SQL by calling `pg` or `postgres` libs directly.
> 
> ORM has a ton of additional functionality that won't be used: relations management, various features like callbacks on create/update/delete, `deletedAt`, and many more. Query builder also has a ton of functionality that is redundant for this: various ways of doing joins, and wrappers for various SQL statements.

Yeah, this is actually something I've hesitated about on bentocache. Do I create adapter for `pg`, `sqlite`, `@libsql/client` etc rather than adapters for ORMs. In the end, I preferred to use ORMs because there are almost more dialects than ORMs. So it seemed simpler to me to maintain the adapters of the most popular ORMs. 

For example, just for Postgres, I would have had to make adapters for `@neondatabase/serverless`, `@xata.io/client`, `pg`, `postgres`, `drizzle-orm/node-postgres` etc... Where I can just add a Drizzle Adapter that will do all this work for me

I hope I didn't make a mistake :sweat_smile:

2024-04-29 18:49 UTC, romeerez commented
Thank you!

It's indeed similar to Lucid, since Lucid is on Knex, and Orchid is syntactically inspired by Knex to be familiar for node.js devs.

Lucid's creator posted some [interesting notes](https://lucid.adonisjs.com/docs/introduction#lucid-is-not-type-safe) about reaching a good type-safety level with ORMs, and this is the exact main goal of Orchid ORM to reach.

2024-04-30 01:18 UTC, bingtsingw commented
@Julien-R44 Hi, I setup the test, seems it fails with `expires_at` column type.
<img width="1043" alt="image" src="https://github.com/Julien-R44/bentocache/assets/10382462/5a9c3266-196b-4195-ada8-54c49f57480f">

2024-04-30 08:59 UTC, Julien-R44 commented
Weird. I'm not sure why. The tests run fine in CI though: https://github.com/Julien-R44/bentocache/actions/runs/8880648142/job/24383374119?pr=17#step:7:128
So i would say, probably a configuration issue on your side

Maybe you can ignore the local execution of the knex tests. Just run the tests you added on Orchid. Or even let the CI execute them

2024-05-15 10:53 UTC, bingtsingw commented
@Julien-R44 Hi, I've completed this pr including `autoCreateTable`.

2024-05-15 10:55 UTC, Julien-R44 commented
Awesome. thanks a lot for taking the time to create this PR. I will give a final look at it and merge it before the end of the week

2024-05-15 11:07 UTC, bingtsingw commented
Some tests did not pass, I took a look at the error messages, not sure if it's related to orchid driver

2024-05-15 19:07 UTC, Julien-R44 commented
Okay that looks perfect to me. Let's merge it. Thanks again for the PR !

2024-05-15 19:07 UTC, merged

2024-05-17 18:28 UTC, Julien-R44 commented
Released with bentocache@1.0.0-beta.9